In [ ]:
#Scrape the list of Arizona-based rock and mineral clubs

In [ ]:
# https://rocktumbler.com/blog/rock-and-mineral-clubs/

In [5]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\larab\.venvs\lede\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\larab\.venvs\lede\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\larab\.venvs\lede\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\larab\.venvs\lede\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\larab\.venvs\lede\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd

In [8]:
!pip install lxml html5lib

Collecting lxml
  Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in C:\Users\larab\.venvs\lede\Lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in C:\Users\larab\.venvs\lede\Lib\site-packages (from html5lib) (0.5.1)
Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------- ----------------------------- 1.0/4.0 MB 5.9 MB/s eta 0:00:01
   -------------------------- ------------- 2.6/4.0 MB 6.1 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 5.8 MB/s  0:00:00
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: lxml, html5lib

   ---------------------------------------- 0/2 [lxml]
   ---------------------------------------- 0/2 [lxml]
   ---------------------------------------- 0/2 [lxml]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   ---------------------------------------- 2/2 [html5lib]

Successfully installed html5lib-1.1 lxml-6.1.1

WARNING: Cache entry deserialization failed, entry ignored

In [11]:
tables = pd.read_html("https://rocktumbler.com/blog/rock-and-mineral-clubs/")
tables

[                                0
 0  Alabama Rock and Mineral Clubs,
                                     0           1
 0  Alabama Mineral & Lapidary Society  Birmingham
 1           Dothan Gem & Mineral Club      Taylor
 2  Huntsville Gem and Mineral Society  Huntsville
 3           Mobile Rock & Gem Society      Mobile
 4    Montgomery Gem & Mineral Society  Montgomery,
                                0
 0  Alaska Rock and Mineral Clubs,
                                0          1
 0  Chugach Gem & Mineral Society  Anchorage
 1   Mat-Su Rock and Mineral Club     Palmer,
                                 0
 0  Arizona Rock and Mineral Clubs,
                                             0                  1
 0           Apache Junction Rock and Gem Club    Apache Junction
 1                 Black Canyon City Rock Club  Black Canyon City
 2          Daisy Mountain Rock & Mineral Club             Anthem
 3           Gila County Gem & Mineral Society              Miami
 4               Huachuca Mineral and Gem Club       Sierra Vista
 5           Lake Havasu Gem & Mineral Society   Lake Havasu City
 6            Mineralogical Society of Arizona         Scottsdale
 7                   Mingus Gem & Mineral Club         Cottonwood
 8                    Mohave County Gemstoners            Kingman
 9                    Old Pueblo Lapidary Club             Tucson
 10              Pinal Gem and Mineral Society           Coolidge
 11                Prescott Gem & Mineral Club  East Chino Valley
 12  Quartzsite Roadrunners Gem & Mineral Club         Quartzsite
 13                            Rockhounds West      Sun City West
 14                  Sedona Gem & Mineral Club             Sedona
 15           Silvery Colorado River Rock Club      Bullhead City
 16              Sunsites Gem and Mineral Club             Pearce
 17             Tucson Gem and Mineral Society             Tucson
 18            West Valley Rock & Mineral Club            Buckeye
 19          White Mountain Gem & Mineral Club           Show Low
 20         Wickenburg Gem and Mineral Society         Wickenburg,
                                  0
 0  Arkansas Rock and Mineral Clubs,
                                                    0               1
 0  Central Arkansas Gem, Mineral and Geology Society     Little Rock
 1           Northwest Arkansas Gem & Mineral Society  Siloam Springs
 2                           Ozark Earth Science Club   Mountain Home,
                                    0
 0  California Rock and Mineral Clubs,
                                                     0                1
 0                               American Opal Society          Anaheim
 1                Antelope Valley Gem and Mineral Club        Lancaster
 2                               Antioch Lapidary Club          Antioch
 3                           Borrego Rock and Gem Club  Borrego Springs
 4                     Calaveras Gem & Mineral Society      Angels Camp
 ..                                                ...              ...
 77                        Vista Gem & Mineral Society            Vista
 78  West Coast Prospectors & Treasure Hunters Asso...     Garden Grove
 79                   West End Prospectors Corporation           Corona
 80                 Woodland Hills Rock Chippers, Inc.       West Hills
 81               Yucaipa Valley Gem & Mineral Society          Yucaipa

 [82 rows x 2 columns],
                                  0
 0  Colorado Rock and Mineral Clubs,
                                            0                 1
 0                    Canon City Geology Club        Canon City
 1                         Colorado Gold Camp         Leadville
 2                   Colorado Mineral Society          Lakewood
 3                        Colorado Prospector           Alamosa
 4     Colorado Springs Mineralogical Society  Colorado Springs
 5          Columbine Gem and Mineral Society            Salida
 6               Denver Gem and Mineral Guild            Denver
 7                     Flatirons Mineral Club           Boulder
 8                    Fort Collins Rockhounds      Fort Collins
 9            Four Corners Gem & Mineral Club           Durango
 10           Four Corners Geological Society           Durango
 11  Friends of Mineralogy - Colorado Chapter            Golden
 12         Grand Junction Gem & Mineral Club    Grand Junction
 13            Lake George Gem & Mineral club       Lake George
 14            Littleton Gem and Mineral Club         Littleton
 15        Mile High Rock and Mineral Society            Arvada
 16               The Paleontological Society       Westminster
 17                         Pueblo Rockhounds            Pueblo
 18  Western Interior Paleontological Society            Denver,
                                     0
 0  Connecticut Rock and Mineral Clubs,
                                                    0          1
 0                         Bristol Gem & Mineral Club    Bristol
 1                      Danbury Mineralogical Society    Danbury
 2                   East Coast Gem & Mineral Society    Ansonia
 3  Lapidary and Mineral Society of Central Connec...    Meriden
 4                             New Haven Mineral Club     Hamden
 5                     Stamford Mineralogical Society  Greenwich,
                                  0
 0  Delaware Rock and Mineral Clubs,
                                 0           1
 0  Delaware Mineralogical Society  Wilmington,
                                 0
 0  Florida Rock and Mineral Clubs,
                                                     0                 1
 0                     Canaveral Mineral & Gem Society         Melbourne
 1                   Central Brevard Rock and Gem Club    Merritt Island
 2             Central Florida Mineral and Gem Society           Orlando
 3                              Florida Fossil Hunters           Orlando
 4            Florida Gold Coast Gem & Mineral Society         Hollywood
 5                           Fossil Club of Lee County         Ft. Myers
 6                   Gainesville Gem & Mineral Society       Gainesville
 7         Gem and Mineral Society of the Palm Beaches   West Palm Beach
 8   Imperial Bone Valley Gem, Mineral, & Fossil So...          Mulberry
 9                Jacksonville Gem and Mineral Society      Jacksonville
 10             Miami Mineralogical and Lapidary Guild             Miami
 11                 Playground Gem and Mineral Society  Ft. Walton Beach
 12                   Southwest Florida Fossil Society       Punta Gorda
 13                 St. Lucie County Rock and Gem Club    Port St. Lucie
 14                     Suncoast Gem & Mineral Society    St. Petersburg
 15                              Tampa Bay Fossil Club             Tampa
 16                   Tampa Bay Mineral & Science Club             Tampa
 17               The Villages Gem and Mineral Society      The Villages
 18                              Tomoka Faceters Guild     Daytona Beach
 19                           Withlacoochee Rockhounds       Spring Hill,
                                 0
 0  Georgia Rock and Mineral Clubs,
                                      0         1
 0             Athens Rock and Gem Club    Athens
 1      Augusta Gem and Mineral Society   Augusta
 2    Cobb County Gem & Mineral Society  Marietta
 3        Georgia Mineral Society, Inc.  Norcross
 4  Mid-Georgia Gem and Mineral Society     Macon
 5    Rome Georgia Mineral Society Inc.      Rome,
                                0
 0  Hawaii Rock and Mineral Clubs,
                                                    0         1
 0  Hui Pohaku 'O Hawai'i Rock & Mineral Society o...  Honolulu,
                               0
 0  Idaho Rock and Mineral Clubs,
                                          0            1
 0              Hells Canyon Gem Club, Inc.     Lewiston
 1        Idaho Falls Gem & Mineral Society  Idaho Falls
 2                     Idaho Gem Club, Inc.        Boise
 3                    Magic Valley Gem Club   Twin Falls
 4                 North Idaho Mineral Club       Hayden
 5             Owyhee Gem & Mineral Society     Caldwell
 6  Southeast Idaho Gem and Mineral Society    Pocatello,
                                  0
 0  Illinois Rock and Mineral Clubs,
                                               0            1
 0                 Black Hawk Gem & Mineral Club  Rock Island
 1              Chicago Rocks & Minerals Society       Skokie
 2         Des Plaines Valley Geological Society  Des Plaines
 3       Earth Science Club of Northern Illinois   Glen Ellyn
 4           Geodeland Earth Science Clubs, Inc.       Macomb
 5           Lincoln Orbit Earth Science Society  Springfield
 6                  Northwest Illinois Rock Club     Freeport
 7   Peoria Academy of Science - Geology Section       Peoria
 8          Southern Illinois Earth Science Club       Benton
 9     West Central Illinois Rock & Mineral Club       Macomb
 10                  West Suburban Lapidary Club     Elmhurst,
                                 0
 0  Indiana Rock and Mineral Clubs,
                                                 0             1
 0                         500 Earth Sciences Club  Indianapolis
 1              Brown County Rock and Mineral Club     Nashville
 2                 Calumet Gem and Mineral Society   Crown Point
 3  Eastern Indiana Gem & Geological Society, Inc.      Richmond
 4                     Evansville Lapidary Society    Evansville
 5                 Lawrence County Rock Club, Inc.       Bedford
 6            Michiana Gem & Mineral Society, Inc.    South Bend
 7              Three Rivers Gem & Mineral Society    Fort Wayne,
                              0
 0  Iowa Rock and Mineral Clubs,
                                          0             1
 0  Cedar Valley Rocks and Minerals Society  Cedar Rapids
 1              Des Moines Lapidary Society    Des Moines
 2           Geology Club @ Cornell College  Mount Vernon
 3       Iowa State University Geology Club          Ames
 4                  River Valley Rockhounds    Fort Dodge,
                                0
 0  Kansas Rock and Mineral Clubs,
                                  0            1
 0   McPherson Gem and Mineral Club    McPherson
 1   Olathe Gem and Mineral Society  Kansas City
 2     Topeka Gem & Mineral Society       Topeka
 3  Wichita Gem and Mineral Society      Wichita
 4  Wichita Paleontological Society      Wichita,
                                  0
 0  Kentucky Rock and Mineral Clubs,
                                   0           1
 0     Blue Grass Gem & Mineral Club   Lexington
 1    Geological Society of Kentucky    Morehead
 2  Kentucky Paleontological Society   Lexington
 3          KYANA Geological Society  Louisville,
                                   0
 0  Louisiana Rock and Mineral Clubs,
                                    0            1
 0   Ark-La-Tex Gem & Mineral Society   Shreveport
 1  Baton Rouge Gem & Mineral Society  Baton Rouge
 2     DeRidder Gem & Mineral Society    Leesville,
                               0
 0  Maine Rock and Mineral Clubs,
                                           0          1
 0                Kennebec Rockhounders Club    Chelsea
 1  Maine Mineralogical & Geological Society   Portland
 2          Midcoast Mineral Collectors Club  Thorndike
 3   Oxford County Mineral & Gem Association     Bethel
 4       Penobscot Mineral and Lapidary Club     Bangor,
                                  0
 0  Maryland Rock and Mineral Clubs,
                                                     0               1
 0                          American Fossil Federation           Bowie
 1                           Baltimore Mineral Society       Baltimore
 2                   Calvert Marine Museum Fossil Club        Solomons
 3   Central Maryland Rock and Mineral Collectors E...        Elkridge
 4                    Chesapeake Gem & Mineral Society       Baltimore
 5                            Clearwater Lapidary Club         Clinton
 6                      Gem Cutters Guild of Baltimore       Baltimore
 7   Gem, Lapidary, and Mineral Society of Montgome...       Rockville
 8                         Maryland Geological Society           Bowie
 9                             Patuxent Lapidary Guild       Annapolis
 10            Southern Maryland Rock and Mineral Club         Waldorf
 11  The Mineralogical Society of the District of C...  Washington, DC,
                                       0
 0  Massachusetts Rock and Mineral Clubs,
                                          0            1
 0                Boston Mineral Club, Inc.    Cambridge
 1          Connecticut Valley Mineral Club  Springfield
 2             Micromounters of New England   Chelmsford
 3     Nashoba Valley Mineralogical Society    Littleton
 4          North Shore Rock & Mineral Club   Burlington
 5          Northern Berkshire Mineral Club  North Adams
 6  Southeastern Massachusetts Mineral Club     Rockland
 7                   Worcester Mineral Club   Shrewsbury,
                                  0
 0  Michigan Rock and Mineral Clubs,
                                                 0                 1
 0   Central Michigan Lapidary and Mineral Society            Okemos
 1            Copper Country Rock and Mineral Club        Dollar Bay
 2                         Flint Rock and Gem Club              Clio
 3       Grand Traverse Area Rock and Mineral Club     Traverse City
 4               Indian Mounds Rock & Mineral Club      Grand Rapids
 5                 Ishpeming Rock and Mineral Club         Ishpeming
 6          Kalamazoo Geological & Mineral Society           Portage
 7                Livingston Gem & Mineral Society            Howell
 8                  Michigan Gem & Mineral Society   Michigan Center
 9                  Michigan Mineralogical Society  Bloomfield Hills
 10                         Mid-Michigan Rock Club           Midland
 11                        Midwest Faceter's Guild       Grand Haven
 12     Midwest Mineralological & Lapidary Society            Taylor
 13                     Mikenauk Rock and Gem Club    Roscommon area
 14             Mt. Clemens Gem & Lapidary Society       Mt. Clemens
 15              Oakland County Earth Science Club         Waterford
 16                                    Roamin Club           Livonia
 17                StateLine Gem & Mineral Society           Morenci
 18                  Tulip City Gem & Mineral Club           Holland
 19                          White River Rock Club          Montague,
                                   0
 0  Minnesota Rock and Mineral Clubs,
                                      0            1
 0      Anoka County Gem & Mineral Club  Robbinsdale
 1    Carlton County Gem & Mineral Club      Cloquet
 2   Cuyuna Rock, Gem & Mineral Society     Brainerd
 3               Minnesota Mineral Club  Bloomington
 4  Minnesota Valley Gem & Mineral Club      Mankato
 5                 St. Croix Rockhounds   Stillwater
 6   Steele County Gem and Mineral Club     Owatonna,
                                     0
 0  Mississippi Rock and Mineral Clubs,
                                                    0              1
 0        Harrison County Gem & Mineral Society, Inc.       Gulfport
 1                Mississippi Gem and Mineral Society       Florence
 2                     Mississippi Geological Society        Jackson
 3  Mississippi Gulf Coast Gem & Mineral Society, ...  Ocean Springs
 4            North Mississippi Gem & Mineral Society         Tupelo,
                                  0
 0  Missouri Rock and Mineral Clubs,
                                              0             1
 0  Central Missouri Rock & Lapidary Club, Inc.      Columbia
 1           Independence Gem & Mineral Society  Independence
 2        Missouri Valley Gem & Mineral Society  Saint Joseph
 3           Mozarkite Society of Lincoln, Inc.       Lincoln
 4                 Ozarks Gem & Mineral Society   Springfield
 5       Rock Hobby Club of Greater Saint Louis     St. Louis
 6               Rockwood Gem & Mineral Society  Chesterfield
 7              St. Louis Mineral & Gem Society     St. Louis
 8           Show Me Gems & Minerals Club, Inc.    St. Peters
 9               Show-Me Rockhounds Kansas City   Kansas City,
                                 0
 0  Montana Rock and Mineral Clubs,
                                          0          1
 0        Billings Gem & Mineral Club, Inc.   Billings
 1         Bitterroot Gem & Mineral Society     Victor
 2             Bozeman Gem and Mineral Club    Bozeman
 3                 Hellgate Mineral Society   Missoula
 4  Northwest Montana Rock Chucks Rock Club  Kalispell,
                                  0
 0  Nebraska Rock and Mineral Clubs,
                                   0        1
 0  Lincoln Gem & Mineral Club, Inc.  Lincoln
 1     Nebraska Mineral and Gem Club    Omaha,
                                0
 0  Nevada Rock and Mineral Clubs,
                                        0            1
 0              Comstock Gold Prospectors       Sparks
 1         Great Basin Gem & Mineral Club  Carson City
 2                    High Desert Rockers  Carson City
 3     Reno Gem and Mineral Society, Inc.       Sparks
 4                            Rock-N-Gold      Pahrump
 5  Southern Nevada Gem & Mineral Society    Las Vegas,
                                       0
 0  New Hampshire Rock and Mineral Clubs,
                                          0           1
 0                     Capital Mineral Club  Canterbury
 1                       Keene Mineral Club       Keene
 2         Saco Valley Gem and Mineral Club      Albany
 3  Southeastern New Hampshire Mineral Club       Dover,
                                    0
 0  New Jersey Rock and Mineral Clubs,
                                             0                  1
 0               Cape Atlantic Rockhounds Inc.       Mays Landing
 1       Delaware Valley Earth Science Society             Berlin
 2  Friends of Mineralogy - New Jersey Chapter  Marlboro Township
 3         Morris Museum Mineralogical Society         Morristown
 4      New Jersey Mineralogical Society, Inc.       Mountainside
 5    North Jersey Mineralogical Society, Inc.           Paterson,
                                    0
 0  New Mexico Rock and Mineral Clubs,
                                                    0            1
 0                     Albuquerque Gem & Mineral Club     Nob Hill
 1                   Carlsbad Gem and Mineral Society     Carlsbad
 2                       Deming Gem & Mineral Society       Deming
 3  Grant County Rolling Stones Gem & Mineral Soci...  Silver City
 4                      New Mexico Geological Society      Socorro,
                                  0
 0  New York Rock and Mineral Clubs,
                                                 0             1
 0                Buffalo Geological Society, Inc.       Buffalo
 1                   Capital District Mineral Club        Albany
 2         Finger Lakes Gem, Mineral & Fossil Club   Canandaigua
 3         Gem & Mineral Society of Syracuse, Inc.     Liverpool
 4           Long Island Mineral & Geology Society     Jamesport
 5   Mid-Hudson Valley Gem & Mineral Society, Inc.  Poughkeepsie
 6                             Nassau Mineral Club     Glen Cove
 7                     New York Mineralogical Club           NYC
 8                New York Paleontological Society           NYC
 9             Orange County Mineral Society, Inc.       Chester
 10                   Rochester Academy of Science     Rochester
 11                     Rochester Lapidary Society     Rochester
 12        St. Lawrence County Rock & Mineral Club        Canton
 13                     Suffolk Gem & Mineral Club     Bay Shore
 14              Wayne County Gem and Mineral Club        Newark,
                                        0

In [ ]:
#ver quantas tabelas foram selecionadas > usando códigos do pandas

In [16]:
len(tables)

113

In [ ]:
# secionar só as do Arizona

In [32]:
tables[1]

                                    0           1
0  Alabama Mineral & Lapidary Society  Birmingham
1           Dothan Gem & Mineral Club      Taylor
2  Huntsville Gem and Mineral Society  Huntsville
3           Mobile Rock & Gem Society      Mobile
4    Montgomery Gem & Mineral Society  Montgomery

In [44]:
df=tables[5]
tables[5]

                                            0                  1
0           Apache Junction Rock and Gem Club    Apache Junction
1                 Black Canyon City Rock Club  Black Canyon City
2          Daisy Mountain Rock & Mineral Club             Anthem
3           Gila County Gem & Mineral Society              Miami
4               Huachuca Mineral and Gem Club       Sierra Vista
5           Lake Havasu Gem & Mineral Society   Lake Havasu City
6            Mineralogical Society of Arizona         Scottsdale
7                   Mingus Gem & Mineral Club         Cottonwood
8                    Mohave County Gemstoners            Kingman
9                    Old Pueblo Lapidary Club             Tucson
10              Pinal Gem and Mineral Society           Coolidge
11                Prescott Gem & Mineral Club  East Chino Valley
12  Quartzsite Roadrunners Gem & Mineral Club         Quartzsite
13                            Rockhounds West      Sun City West
14                  Sedona Gem & Mineral Club             Sedona
15           Silvery Colorado River Rock Club      Bullhead City
16              Sunsites Gem and Mineral Club             Pearce
17             Tucson Gem and Mineral Society             Tucson
18            West Valley Rock & Mineral Club            Buckeye
19          White Mountain Gem & Mineral Club           Show Low
20         Wickenburg Gem and Mineral Society         Wickenburg

In [ ]:
#salvar como csv

In [46]:
df.to_csv("arizona_rocks.csv", index=False)